# Generated by Django 6.0.7 on 2026-07-20 07:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NCFRMIMonthlyReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_month", models.PositiveIntegerField(help_text="1-12")),
                ("report_year", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("total_migrants_registered", models.PositiveIntegerField(default=0)),
                ("total_cases_opened", models.PositiveIntegerField(default=0)),
                ("total_cases_resolved", models.PositiveIntegerField(default=0)),
                ("total_referrals_made", models.PositiveIntegerField(default=0)),
                ("total_referrals_completed", models.PositiveIntegerField(default=0)),
                ("returnees_assisted", models.PositiveIntegerField(default=0)),
                ("vulnerable_cases_identified", models.PositiveIntegerField(default=0)),
                ("protection_incidents", models.PositiveIntegerField(default=0)),
                ("hotspot_alerts_issued", models.PositiveIntegerField(default=0)),
                ("lga_breakdown", models.JSONField(blank=True, default=dict)),
                ("challenges", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved by State Coordinator"),
                            ("submitted", "Submitted to NCFRMI Abuja"),
                            ("acknowledged", "Acknowledged by NCFRMI"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submitted_to_ncfrmi_at", models.DateTimeField(blank=True, null=True)),
                ("ncfrmi_reference", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_ncfrmi_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ncfrmi_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-report_year", "-report_month"],
            },
        ),
        migrations.CreateModel(
            name="NCFRMISubmissionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_logs",
                        to="ncfrmi_reporting.ncfrmimonthlyreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ncfrmimonthlyreport",
            index=models.Index(
                fields=["status", "-report_year", "-report_month"],
                name="ncfrmi_repo_status_53b71a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ncfrmimonthlyreport",
            unique_together={("report_month", "report_year", "prepared_by")},
        ),
    ]
