# Generated by Django 6.0.7 on 2026-07-19 21:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RateLimitLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("endpoint", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("was_throttled", models.BooleanField(default=False)),
                ("request_count", models.PositiveIntegerField(default=1)),
                ("window_start", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ip_address", "-created_at"],
                        name="throttle_ra_ip_addr_d490f7_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="throttle_ra_user_id_80a9a6_idx",
                    ),
                    models.Index(
                        fields=["endpoint", "-created_at"],
                        name="throttle_ra_endpoin_4a6919_idx",
                    ),
                ],
            },
        ),
    ]
