# Generated by Django 6.0.7 on 2026-07-20 07:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GIZIndicator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(default="general", max_length=50)),
                ("target_value", models.PositiveIntegerField(default=0)),
                ("current_value", models.PositiveIntegerField(default=0)),
                ("unit", models.CharField(default="count", max_length=50)),
                (
                    "programme_area",
                    models.CharField(
                        choices=[
                            ("migration_governance", "Migration Governance"),
                            ("labour_migration", "Labour Migration"),
                            ("diaspora_engagement", "Diaspora Engagement"),
                            ("protection_assistance", "Protection & Assistance"),
                            ("reintegration", "Reintegration Support"),
                            ("skills_development", "Skills Development"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "reporting_period",
                    models.CharField(default="Q3-2026", max_length=50),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["programme_area", "name"],
            },
        ),
        migrations.CreateModel(
            name="GIZDataExchange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "programme_area",
                    models.CharField(
                        choices=[
                            ("migration_governance", "Migration Governance"),
                            ("labour_migration", "Labour Migration"),
                            ("diaspora_engagement", "Diaspora Engagement"),
                            ("protection_assistance", "Protection & Assistance"),
                            ("reintegration", "Reintegration Support"),
                            ("skills_development", "Skills Development"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "data_payload",
                    models.JSONField(
                        default=dict, help_text="Structured data for GIZ reporting"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted to GIZ"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("implemented", "Implemented"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "giz_project_code",
                    models.CharField(
                        blank=True, help_text="GIZ project reference", max_length=50
                    ),
                ),
                ("giz_feedback", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["programme_area", "status"],
                        name="giz_gizdata_program_fd7453_idx",
                    ),
                    models.Index(
                        fields=["giz_project_code"],
                        name="giz_gizdata_giz_pro_796951_idx",
                    ),
                ],
            },
        ),
    ]
