# Generated by Django 6.0.7 on 2026-07-20 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IOMConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("api_base_url", models.URLField(default="https://api.iom.int/v1")),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("client_id", models.CharField(blank=True, max_length=100)),
                ("client_secret", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_sync_enabled", models.BooleanField(default=False)),
                ("sync_interval_hours", models.PositiveIntegerField(default=24)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "IOM Configuration",
                "verbose_name_plural": "IOM Configurations",
            },
        ),
        migrations.CreateModel(
            name="IOMDataExchange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("outbound", "To IOM"), ("inbound", "From IOM")],
                        max_length=10,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("migrant", "Migrant Profile"),
                            ("case", "Case Record"),
                            ("referral", "Referral"),
                            ("assessment", "Needs Assessment"),
                            ("protection", "Protection Incident"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(help_text="Local entity ID", max_length=100),
                ),
                (
                    "iom_reference",
                    models.CharField(
                        blank=True, help_text="IOM system reference", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected by IOM"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("response_data", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "status"],
                        name="iom_iomdata_entity__cf3526_idx",
                    ),
                    models.Index(
                        fields=["direction", "-created_at"],
                        name="iom_iomdata_directi_297ac4_idx",
                    ),
                ],
            },
        ),
    ]
