# Generated by Django 4.2.30 on 2026-07-11 10:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrant',
            name='gps_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='GPS coordinates captured by ODK Collect', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='migrant',
            name='odk_submission_id',
            field=models.CharField(blank=True, db_index=True, help_text='ODK Central submission ID for duplicate detection', max_length=100, null=True),
        ),
    ]
