# Generated by Django 6.0.7 on 2026-07-19 19:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotspotPrediction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("risk_score", models.FloatField(help_text="0.0 to 1.0")),
                ("predicted_migrant_count", models.PositiveIntegerField()),
                (
                    "contributing_factors",
                    models.JSONField(
                        default=dict, help_text="AI-identified risk factors"
                    ),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("analysis_period_start", models.DateField()),
                ("analysis_period_end", models.DateField()),
                ("model_version", models.CharField(default="v1.0", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotspot_predictions",
                        to="accounts.lga",
                    ),
                ),
            ],
            options={
                "ordering": ["-risk_score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["lga", "-risk_score"],
                        name="hotspot_hot_lga_id_b7a58d_idx",
                    ),
                    models.Index(
                        fields=["risk_level", "-created_at"],
                        name="hotspot_hot_risk_le_c8c031_idx",
                    ),
                ],
            },
        ),
    ]
