# Generated by Django 6.0.7 on 2026-07-19 22:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartDashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("bar", "Bar Chart"),
                            ("line", "Line Chart"),
                            ("pie", "Pie Chart"),
                            ("doughnut", "Doughnut Chart"),
                            ("radar", "Radar Chart"),
                            ("geo", "Geo Map"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        help_text="e.g. migrants, cases, referrals", max_length=50
                    ),
                ),
                (
                    "query_config",
                    models.JSONField(
                        default=dict, help_text="filter, group_by, aggregation"
                    ),
                ),
                (
                    "chart_config",
                    models.JSONField(
                        blank=True, default=dict, help_text="Chart.js configuration"
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
