# Generated by Django 6.0.7 on 2026-07-19 00:01

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
        ("migrants", "0004_photouploadqueue_migrantversion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPredictionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prediction_type",
                    models.CharField(
                        choices=[
                            ("risk_assessment", "Risk Assessment"),
                            ("case_priority", "Case Priority"),
                            ("referral_match", "Referral Match"),
                            ("fraud_detection", "Fraud Detection"),
                        ],
                        max_length=30,
                    ),
                ),
                ("input_data", models.JSONField()),
                ("output_data", models.JSONField()),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("model_used", models.CharField(max_length=100)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="riskassessment",
            name="ai_model",
        ),
        migrations.RemoveField(
            model_name="predictionlog",
            name="ai_model",
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="model_version",
            field=models.CharField(default="ollama:llama3", max_length=50),
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="raw_response",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="riskassessment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="factors",
            field=models.JSONField(default=dict, help_text="Detected risk factors"),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="recommendations",
            field=models.JSONField(default=list, help_text="AI recommendations"),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="low",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="risk_score",
            field=models.FloatField(default=0.0, help_text="0.0 to 1.0"),
        ),
        migrations.AddIndex(
            model_name="riskassessment",
            index=models.Index(
                fields=["risk_level", "created_at"],
                name="ai_riskasse_risk_le_b3cb30_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="riskassessment",
            index=models.Index(
                fields=["migrant", "-created_at"], name="ai_riskasse_migrant_55bd70_idx"
            ),
        ),
        migrations.DeleteModel(
            name="AIModel",
        ),
        migrations.DeleteModel(
            name="PredictionLog",
        ),
    ]
