# Generated by Django 4.2.30 on 2026-07-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migrants', '0002_migrant_gps_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='migrant',
            name='id_number_encrypted',
            field=models.TextField(blank=True, help_text='AES-256 encrypted NIN or passport number', null=True),
        ),
        migrations.AddField(
            model_name='migrant',
            name='id_number_plaintext',
            field=models.CharField(blank=True, help_text='Temporary plaintext (dev only — remove before production)', max_length=50, null=True),
        ),
    ]
