# Generated by Django 6.0.7 on 2026-07-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("migrants", "0004_photouploadqueue_migrantversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="migrant",
            name="current_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="migrant",
            name="current_lga_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="migrant",
            name="current_state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="migrant",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "No Formal Education"),
                    ("informal", "Informal Education"),
                    ("primary", "Primary"),
                    ("secondary", "Secondary"),
                    ("tertiary", "Tertiary"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="migrant",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="migrant",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="migrant",
            name="emergency_contact_relationship",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="migrant",
            name="has_children",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="migrant",
            name="health_condition",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="migrant",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("widowed", "Widowed"),
                    ("divorced", "Divorced"),
                    ("separated", "Separated"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="migrant",
            name="number_of_children",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="migrant",
            name="purpose_of_migration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("work", "Work / Employment"),
                    ("business", "Business / Trade"),
                    ("education", "Education"),
                    ("family", "Family Reunion"),
                    ("refugee", "Refugee / Asylum"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="migrant",
            name="registration_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="migrant",
            name="source",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("self_service", "Self-Service Portal"),
                    ("import", "Bulk Import"),
                ],
                default="admin",
                max_length=50,
            ),
        ),
    ]
