#!/usr/bin/env bash
#===============================================================================
# ABIA MIGRATION OBSERVATORY — TEST ENVIRONMENT FIX SCRIPT
# Auto-detects environment and configures Django database settings
#===============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${SCRIPT_DIR}"
APP_DIR="${PROJECT_ROOT}/abia-app"
DOCKER_DIR="${PROJECT_ROOT}/abia-core/docker"

echo "========================================"
echo "  ABIA TEST ENVIRONMENT FIX SCRIPT"
echo "========================================"
echo ""

#===============================================================================
# STEP 1: DETECT ENVIRONMENT
#===============================================================================
echo "[1/6] Detecting environment..."

INSIDE_DOCKER=false
if [ -f /.dockerenv ] || grep -q docker /proc/1/cgroup 2>/dev/null; then
    INSIDE_DOCKER=true
    echo "      → Running INSIDE Docker container"
else
    echo "      → Running OUTSIDE Docker (WSL/host)"
fi

# Check if postgres container is running
POSTGRES_RUNNING=false
if docker ps --format '{{.Names}}' | grep -q 'abia-postgres'; then
    POSTGRES_RUNNING=true
    echo "      → PostgreSQL container: RUNNING ✓"
else
    echo "      → PostgreSQL container: NOT RUNNING ✗"
fi

# Check if port 5432 is accessible on localhost
PG_HOST="localhost"
PG_PORT="5432"
if command -v nc &>/dev/null; then
    if nc -z localhost 5432 2>/dev/null; then
        echo "      → PostgreSQL port 5432 on localhost: OPEN ✓"
    else
        echo "      → PostgreSQL port 5432 on localhost: CLOSED ✗"
        PG_HOST="postgres"
    fi
elif command -v pg_isready &>/dev/null; then
    if pg_isready -h localhost -p 5432 &>/dev/null; then
        echo "      → PostgreSQL port 5432 on localhost: OPEN ✓"
    else
        echo "      → PostgreSQL port 5432 on localhost: CLOSED ✗"
        PG_HOST="postgres"
    fi
else
    echo "      → Cannot test port, assuming localhost for WSL"
fi

#===============================================================================
# STEP 2: FIX DOCKER COMPOSE YAML (if malformed)
#===============================================================================
echo ""
echo "[2/6] Checking Docker Compose configuration..."

COMPOSE_FILE="${DOCKER_DIR}/docker-compose.yml"
if [ -f "$COMPOSE_FILE" ]; then
    # Check if YAML has correct indentation
    if grep -q "^services:" "$COMPOSE_FILE" 2>/dev/null; then
        echo "      → docker-compose.yml structure looks OK"
    else
        echo "      → WARNING: docker-compose.yml may be malformed"
        echo "      → Attempting to fix..."

        cat > "$COMPOSE_FILE" << 'EOF'
version: "3.9"

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: abia-postgres
    environment:
      POSTGRES_DB: abia_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - abia-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - abia-network

  redis:
    image: redis:7-alpine
    container_name: abia-redis
    networks:
      - abia-network

  django:
    build:
      context: ../../abia-app
      dockerfile: Dockerfile
    container_name: abia-django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../../abia-app:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=abia.settings
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD:-changeme}@postgres:5432/abia_app
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - abia-network

volumes:
  abia-postgres-data:

networks:
  abia-network:
    name: abia-network
    driver: bridge
EOF
        echo "      → docker-compose.yml FIXED ✓"
    fi
else
    echo "      → docker-compose.yml not found at expected path"
    echo "        Expected: ${COMPOSE_FILE}"
fi

#===============================================================================
# STEP 3: CREATE TEST-SPECIFIC DJANGO SETTINGS
#===============================================================================
echo ""
echo "[3/6] Creating test settings..."

TEST_SETTINGS_FILE="${APP_DIR}/abia/test_settings.py"
mkdir -p "$(dirname "$TEST_SETTINGS_FILE")"

cat > "$TEST_SETTINGS_FILE" << EOF
# Test settings for running pytest outside Docker
# Auto-generated by fix_test_env.sh

from .settings import *

# Override database for WSL/local testing
# When running outside Docker, connect to PostgreSQL via localhost
# The postgres container exposes port 5432 to the host
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.getenv('POSTGRES_DB', 'abia_app_test'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'changeme'),
        'HOST': os.getenv('POSTGRES_HOST', '${PG_HOST}'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}

# Use faster password hasher for tests
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.MD5PasswordHasher',
]

# Disable migrations for faster tests (optional — comment out if you need migrations)
# class DisableMigrations:
#     def __contains__(self, item):
#         return True
#     def __getitem__(self, item):
#         return None
# MIGRATION_MODULES = DisableMigrations()

# Celery run synchronously in tests
CELERY_TASK_ALWAYS_EAGER = True
CELERY_TASK_EAGER_PROPAGATES = True

# Disable caching in tests
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}
EOF

echo "      → Created: ${TEST_SETTINGS_FILE}"

#===============================================================================
# STEP 4: CREATE PYTEST CONFIGURATION
#===============================================================================
echo ""
echo "[4/6] Creating pytest configuration..."

PYTEST_INI="${APP_DIR}/pytest.ini"
cat > "$PYTEST_INI" << 'EOF'
[pytest]
DJANGO_SETTINGS_MODULE = abia.test_settings
python_files = tests.py test_*.py *_tests.py
addopts = -v --tb=short --reuse-db

# Markers
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks tests as integration tests
    unit: marks tests as unit tests
EOF

echo "      → Created: ${PYTEST_INI}"

# Also create setup.cfg as fallback
SETUP_CFG="${APP_DIR}/setup.cfg"
cat > "$SETUP_CFG" << 'EOF'
[tool:pytest]
DJANGO_SETTINGS_MODULE = abia.test_settings
python_files = tests.py test_*.py *_tests.py
addopts = -v --tb=short --reuse-db
EOF

echo "      → Created: ${SETUP_CFG}"

#===============================================================================
# STEP 5: CREATE TEST DATABASE IF NEEDED
#===============================================================================
echo ""
echo "[5/6] Ensuring test database exists..."

TEST_DB_NAME="${POSTGRES_DB:-abia_app_test}"
TEST_DB_USER="${POSTGRES_USER:-postgres}"
TEST_DB_PASS="${POSTGRES_PASSWORD:-changeme}"
TEST_DB_HOST="${PG_HOST}"
TEST_DB_PORT="${POSTGRES_PORT:-5432}"

# Try to create test database using docker exec
if [ "$POSTGRES_RUNNING" = true ]; then
    echo "      → Creating test database (if not exists)..."
    docker exec abia-postgres psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = '${TEST_DB_NAME}'" | grep -q 1 ||         docker exec abia-postgres psql -U postgres -c "CREATE DATABASE ${TEST_DB_NAME};" 2>/dev/null || true
    echo "      → Test database ready ✓"
else
    echo "      → WARNING: Cannot create test database — PostgreSQL not running"
    echo "        Run: docker compose -f ${DOCKER_DIR}/docker-compose.yml up -d postgres"
fi

#===============================================================================
# STEP 6: CREATE CONVENIENCE RUNNER SCRIPTS
#===============================================================================
echo ""
echo "[6/6] Creating convenience scripts..."

# Run tests script
RUN_TESTS="${PROJECT_ROOT}/run_tests.sh"
cat > "$RUN_TESTS" << 'EOF'
#!/usr/bin/env bash
# Run tests with correct settings
set -e

cd "$(dirname "$0")/abia-app"

echo "Running tests with abia.test_settings..."
export PYTHONPATH="${PYTHONPATH}:$(pwd)"

# Use pytest-django with our test settings
pytest "$@"
EOF
chmod +x "$RUN_TESTS"
echo "      → Created: ${RUN_TESTS}"

# Quick test script (faster, no migrations)
QUICK_TEST="${PROJECT_ROOT}/quick_test.sh"
cat > "$QUICK_TEST" << 'EOF'
#!/usr/bin/env bash
# Quick test run — reuses database, no migration overhead
set -e

cd "$(dirname "$0")/abia-app"

echo "Running quick tests (--reuse-db --no-migrations)..."
export PYTHONPATH="${PYTHONPATH}:$(pwd)"

pytest --reuse-db --no-migrations -x "$@"
EOF
chmod +x "$QUICK_TEST"
echo "      → Created: ${QUICK_TEST}"

# Docker-based test runner
DOCKER_TEST="${PROJECT_ROOT}/run_tests_docker.sh"
cat > "$DOCKER_TEST" << 'EOF'
#!/usr/bin/env bash
# Run tests inside Docker (full environment)
set -e

DOCKER_DIR="$(dirname "$0")/abia-core/docker"

echo "Starting services..."
docker compose -f "${DOCKER_DIR}/docker-compose.yml" up -d postgres redis

echo "Waiting for PostgreSQL..."
sleep 3

echo "Running tests in Django container..."
docker compose -f "${DOCKER_DIR}/docker-compose.yml" exec django pytest "$@"
EOF
chmod +x "$DOCKER_TEST"
echo "      → Created: ${DOCKER_TEST}"

#===============================================================================
# DONE
#===============================================================================
echo ""
echo "========================================"
echo "  FIX COMPLETE ✓"
echo "========================================"
echo ""
echo "You can now run tests using:"
echo ""
echo "  1. WSL/Local (FASTEST — recommended for dev):"
echo "     ./run_tests.sh"
echo "     ./quick_test.sh          # Even faster, reuses DB"
echo ""
echo "  2. Inside Docker (FULL environment):"
echo "     ./run_tests_docker.sh"
echo "     OR: docker compose -f abia-core/docker/docker-compose.yml exec django pytest"
echo ""
echo "Environment variables set:"
echo "  POSTGRES_HOST=${PG_HOST}"
echo "  POSTGRES_PORT=${PG_PORT}"
echo "  POSTGRES_DB=${TEST_DB_NAME}"
echo "  POSTGRES_USER=${TEST_DB_USER}"
echo ""
echo "If tests still fail, ensure PostgreSQL is running:"
echo "  docker compose -f abia-core/docker/docker-compose.yml up -d postgres"
echo ""
