[pytest]
DJANGO_SETTINGS_MODULE = abia.settings
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --reuse-db --no-migrations -p no:cacheprovider
norecursedirs =
    dynamic_fields
    dynamic_fields_backup_*
    fix_*
    .git
    .venv
    node_modules
    accounts
    cases
    migrants
    referrals
