services:
  - type: web
    name: abia-migration
    runtime: python
    plan: free
    region: oregon
    buildCommand: |
      pip install -r requirements.txt && 
      cd abia-app && 
      python manage.py collectstatic --no-input &&
      python manage.py migrate --no-input
    startCommand: cd abia-app && gunicorn abia.wsgi:application --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: abia-postgres
          property: connectionString
databases:
  - name: abia-postgres
    databaseName: abia_migration
    user: abia
    plan: free
    region: oregon
