# Generated by Django 6.0.7 on 2026-08-03 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityAwarenessEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("town_hall", "Town Hall Meeting"),
                            ("religious", "Religious Gathering"),
                            ("market", "Market Sensitization"),
                            ("school", "School Program"),
                            ("media", "Media Campaign"),
                            ("door_to_door", "Door-to-Door"),
                        ],
                        max_length=20,
                    ),
                ),
                ("venue", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("attendance_count", models.PositiveIntegerField(default=0)),
                ("materials_distributed", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "facilitator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awareness_events",
                        to="accounts.lga",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourtCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_number", models.CharField(max_length=50, unique=True)),
                ("court_name", models.CharField(max_length=200)),
                ("charges", models.TextField()),
                ("prosecuting_officer", models.CharField(max_length=100)),
                (
                    "prosecution_agency",
                    models.CharField(default="NAPTIP", max_length=100),
                ),
                ("defense_counsel", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("arraigned", "Arraigned"),
                            ("trial", "Trial"),
                            ("adjourned", "Adjourned"),
                            ("convicted", "Convicted"),
                            ("acquitted", "Acquitted"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("next_hearing_date", models.DateField(blank=True, null=True)),
                ("verdict", models.TextField(blank=True)),
                ("sentence", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "court_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.lga",
                    ),
                ),
            ],
            options={
                "ordering": ["-next_hearing_date"],
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photograph"),
                            ("document", "Document"),
                            ("video", "Video Recording"),
                            ("audio", "Audio Recording"),
                            ("statement", "Witness Statement"),
                            ("medical", "Medical Report"),
                            ("digital", "Digital Evidence"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="evidence/%Y/%m/"
                    ),
                ),
                (
                    "ipfs_hash",
                    models.CharField(
                        blank=True, help_text="IPFS content identifier", max_length=100
                    ),
                ),
                ("ipfs_url", models.URLField(blank=True)),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                ("chain_of_custody", models.TextField(blank=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="anti_trafficking.courtcase",
                    ),
                ),
                (
                    "collected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FakeJobAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agency_name", models.CharField(max_length=200)),
                ("contact_person", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("promised_job", models.CharField(max_length=200)),
                ("promised_salary", models.CharField(blank=True, max_length=100)),
                ("fees_demanded", models.CharField(blank=True, max_length=100)),
                ("destination_country", models.CharField(blank=True, max_length=100)),
                ("reporter_name", models.CharField(blank=True, max_length=100)),
                ("reporter_phone", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("under_investigation", "Under Investigation"),
                            ("verified_fake", "Verified Fake"),
                            ("verified_legitimate", "Verified Legitimate"),
                            ("blacklisted", "Blacklisted"),
                        ],
                        default="reported",
                        max_length=30,
                    ),
                ),
                ("verification_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.lga",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Perpetrator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "aliases",
                    models.TextField(
                        blank=True, help_text="Known aliases, separated by commas"
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                ("phone_numbers", models.TextField(blank=True)),
                ("known_addresses", models.TextField(blank=True)),
                (
                    "modus_operandi",
                    models.TextField(
                        help_text="Method of recruitment and exploitation"
                    ),
                ),
                ("known_associates", models.TextField(blank=True)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lga_of_operation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="perpetrators",
                        to="accounts.lga",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("view_perpetrator_database", "Can view perpetrator database")
                ],
            },
        ),
        migrations.AddField(
            model_name="courtcase",
            name="perpetrator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="court_cases",
                to="anti_trafficking.perpetrator",
            ),
        ),
        migrations.CreateModel(
            name="SchoolProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=200)),
                ("program_date", models.DateField()),
                ("students_reached", models.PositiveIntegerField(default=0)),
                ("peer_educators_trained", models.PositiveIntegerField(default=0)),
                (
                    "topics_covered",
                    models.JSONField(
                        default=list,
                        help_text="['safe_migration','trafficking_signs','reporting']",
                    ),
                ),
                (
                    "facilitator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_programs",
                        to="accounts.lga",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shelter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("capacity", models.PositiveIntegerField()),
                ("current_occupancy", models.PositiveIntegerField(default=0)),
                ("manager_name", models.CharField(max_length=100)),
                ("manager_phone", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "lga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelters",
                        to="accounts.lga",
                    ),
                ),
            ],
            options={
                "verbose_name": "Safe House / Shelter",
            },
        ),
        migrations.CreateModel(
            name="VictimIntake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "trafficking_route",
                    models.TextField(help_text="e.g. Aba → Lagos → Libya"),
                ),
                (
                    "exploitation_type",
                    models.CharField(
                        choices=[
                            ("sexual", "Sexual Exploitation"),
                            ("labor", "Forced Labor"),
                            ("domestic", "Domestic Servitude"),
                            ("organ", "Organ Trafficking"),
                            ("child_soldier", "Child Soldier"),
                            ("forced_marriage", "Forced Marriage"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("perpetrator_description", models.TextField(blank=True)),
                (
                    "immediate_needs",
                    models.JSONField(
                        default=list,
                        help_text="['medical','legal','shelter','psychosocial']",
                    ),
                ),
                (
                    "consent_data_sharing",
                    models.BooleanField(
                        default=False, help_text="Consent to share with NAPTIP"
                    ),
                ),
                ("consent_family_contact", models.BooleanField(default=False)),
                ("intake_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rescued", "Rescued"),
                            ("referred", "Referred"),
                            ("shelter", "In Shelter"),
                            ("rehabilitation", "Rehabilitation"),
                            ("reintegrated", "Reintegrated"),
                        ],
                        default="rescued",
                        max_length=20,
                    ),
                ),
                ("synced_to_naptip", models.BooleanField(default=False)),
                ("naptip_reference", models.CharField(blank=True, max_length=100)),
                (
                    "assigned_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_lga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="victims_in",
                        to="accounts.lga",
                    ),
                ),
                (
                    "lga_of_origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="victims_from",
                        to="accounts.lga",
                    ),
                ),
            ],
            options={
                "verbose_name": "Victim Intake",
                "verbose_name_plural": "Victim Intakes",
                "ordering": ["-intake_date"],
            },
        ),
        migrations.CreateModel(
            name="ShelterStay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_admitted", models.DateTimeField(auto_now_add=True)),
                ("date_discharged", models.DateTimeField(blank=True, null=True)),
                (
                    "discharge_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("reunified", "Family Reunified"),
                            ("independent", "Independent Living"),
                            ("transferred", "Transferred"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stays",
                        to="anti_trafficking.shelter",
                    ),
                ),
                (
                    "victim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelter_stays",
                        to="anti_trafficking.victimintake",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shelter Stay",
            },
        ),
        migrations.CreateModel(
            name="ReintegrationPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "family_reunification_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("dna_testing", "DNA Testing"),
                            ("home_visit", "Home Visit Conducted"),
                            ("reunified", "Reunified"),
                            ("alternative_care", "Alternative Care Arranged"),
                        ],
                        max_length=50,
                    ),
                ),
                ("vocational_skill", models.CharField(blank=True, max_length=100)),
                ("training_center", models.CharField(blank=True, max_length=200)),
                ("training_start_date", models.DateField(blank=True, null=True)),
                ("training_completion_date", models.DateField(blank=True, null=True)),
                (
                    "business_grant_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("business_type", models.CharField(blank=True, max_length=100)),
                (
                    "business_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("planning", "Planning"),
                            ("funded", "Funded"),
                            ("operational", "Operational"),
                            ("failed", "Failed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "victim",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reintegration_plan",
                        to="anti_trafficking.victimintake",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PsychosocialSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_date", models.DateTimeField()),
                (
                    "trauma_score",
                    models.PositiveIntegerField(
                        blank=True, help_text="1-10 scale", null=True
                    ),
                ),
                ("notes", models.TextField()),
                ("next_session_date", models.DateField(blank=True, null=True)),
                (
                    "counselor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "victim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="psychosocial_sessions",
                        to="anti_trafficking.victimintake",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MissingPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("last_seen_location", models.CharField(max_length=200)),
                ("last_seen_date", models.DateField()),
                (
                    "description",
                    models.TextField(
                        help_text="Physical description, clothing, distinguishing marks"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="missing_persons/"
                    ),
                ),
                ("reporter_name", models.CharField(max_length=100)),
                ("reporter_phone", models.CharField(max_length=20)),
                ("reporter_relationship", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("missing", "Missing"),
                            ("located", "Located"),
                            ("intercepted", "Intercepted at Border"),
                            ("deceased", "Deceased"),
                            ("reunified", "Reunified"),
                        ],
                        default="missing",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="missing_persons",
                        to="accounts.lga",
                    ),
                ),
                (
                    "matched_victim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="missing_person_matches",
                        to="anti_trafficking.victimintake",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FamilyReunification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("family_contact_name", models.CharField(max_length=200)),
                ("family_phone", models.CharField(max_length=20)),
                ("family_address", models.TextField()),
                ("dna_test_required", models.BooleanField(default=False)),
                (
                    "dna_test_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("sample_collected", "Sample Collected"),
                            ("in_lab", "In Laboratory"),
                            ("matched", "Matched"),
                            ("not_matched", "Not Matched"),
                        ],
                        max_length=50,
                    ),
                ),
                ("home_visit_conducted", models.BooleanField(default=False)),
                ("home_visit_date", models.DateField(blank=True, null=True)),
                ("home_visit_report", models.TextField(blank=True)),
                ("reunification_date", models.DateField(blank=True, null=True)),
                ("is_safe_placement", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                (
                    "family_lga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="family_reunifications",
                        to="accounts.lga",
                    ),
                ),
                (
                    "victim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_reunifications",
                        to="anti_trafficking.victimintake",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="courtcase",
            name="victim",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="court_cases",
                to="anti_trafficking.victimintake",
            ),
        ),
    ]
