# Generated by Django 6.0.7 on 2026-07-19 22:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MapLayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "layer_type",
                    models.CharField(
                        choices=[
                            ("lga_boundary", "LGA Boundary"),
                            ("migrant_cluster", "Migrant Cluster"),
                            ("case_hotspot", "Case Hotspot"),
                            ("referral_route", "Referral Route"),
                            ("custom", "Custom Layer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "geojson_data",
                    models.JSONField(
                        default=dict, help_text="GeoJSON FeatureCollection"
                    ),
                ),
                (
                    "style_config",
                    models.JSONField(
                        blank=True, default=dict, help_text="Leaflet style options"
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=False)),
                ("z_index", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["z_index", "-created_at"],
            },
        ),
    ]
