# Generated by Django 6.0.7 on 2026-08-07 02:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deployment_date", models.DateField()),
                ("contract_start", models.DateField()),
                ("contract_end", models.DateField(blank=True, null=True)),
                (
                    "salary_agreed_usd",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("accommodation_provided", models.BooleanField(default=False)),
                (
                    "accommodation_quality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("good", "Good"),
                            ("adequate", "Adequate"),
                            ("poor", "Poor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "welfare_status",
                    models.CharField(
                        choices=[
                            ("good", "Good — No concerns"),
                            ("concern", "Concern — Minor issues"),
                            ("critical", "Critical — Intervention required"),
                            ("resolved", "Resolved — Issue closed"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("last_welfare_check", models.DateField(blank=True, null=True)),
                ("embassy_notified", models.BooleanField(default=False)),
                ("anonymised_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-deployment_date"],
            },
        ),
        migrations.CreateModel(
            name="EmbassyMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                (
                    "mission_type",
                    models.CharField(
                        choices=[
                            ("embassy", "Embassy"),
                            ("consulate", "Consulate"),
                            ("high_commission", "High Commission"),
                            ("liaison", "Liaison Office"),
                        ],
                        max_length=20,
                    ),
                ),
                ("mission_name", models.CharField(max_length=300)),
                ("labour_attache_name", models.CharField(blank=True, max_length=200)),
                ("labour_attache_email", models.EmailField(blank=True, max_length=254)),
                ("labour_attache_phone", models.CharField(blank=True, max_length=30)),
                ("mou_signed", models.BooleanField(default=False)),
                ("mou_date", models.DateField(blank=True, null=True)),
                (
                    "bla_aligned",
                    models.BooleanField(
                        default=False, verbose_name="Bilateral Labour Agreement Aligned"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Embassy / Mission",
                "ordering": ["country", "city"],
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="GrievanceTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_number", models.CharField(max_length=30, unique=True)),
                ("reported_date", models.DateField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("unpaid_wages", "Unpaid Wages"),
                            ("abuse", "Abuse/Mistreatment"),
                            ("contract_breach", "Contract Breach"),
                            ("poor_accommodation", "Poor Accommodation"),
                            ("medical_neglect", "Medical Neglect"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("escalated", "Escalated to Embassy"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateField(blank=True, null=True)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grievances",
                        to="talent_exchange.deployment",
                    ),
                ),
            ],
            options={
                "ordering": ["-reported_date"],
            },
        ),
        migrations.CreateModel(
            name="Occupation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("skills_required", models.TextField(blank=True)),
                ("experience_years_min", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupations",
                        to="talent_exchange.sector",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ForeignEmployer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=300)),
                ("trading_name", models.CharField(blank=True, max_length=300)),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "company_reg",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Company Registration / Tax ID",
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                (
                    "compliance_tier",
                    models.CharField(
                        choices=[
                            ("platinum", "Platinum — Exemplary"),
                            ("gold", "Gold — Compliant"),
                            ("silver", "Silver — Monitoring"),
                            ("bronze", "Bronze — Review Required"),
                            ("blacklisted", "Blacklisted"),
                        ],
                        default="silver",
                        max_length=20,
                    ),
                ),
                (
                    "compliance_score",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("embassy_verified", models.BooleanField(default=False)),
                ("verification_date", models.DateField(blank=True, null=True)),
                ("total_workers_sourced", models.PositiveIntegerField(default=0)),
                ("active_workers", models.PositiveIntegerField(default=0)),
                ("worker_complaints", models.PositiveIntegerField(default=0)),
                (
                    "contract_compliance_rate",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "avg_salary_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("blacklist_reason", models.TextField(blank=True)),
                ("blacklisted_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verified_by_mission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="talent_exchange.embassymission",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="talent_exchange.sector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foreign Employer",
                "ordering": ["-compliance_score", "company_name"],
            },
        ),
        migrations.CreateModel(
            name="TalentPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "japa_beneficiary_id",
                    models.CharField(
                        blank=True,
                        help_text="Link to japa_development.Beneficiary",
                        max_length=50,
                    ),
                ),
                (
                    "observatory_person_id",
                    models.CharField(
                        blank=True, help_text="Link to migrants.Migrant", max_length=50
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("lga", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("years_experience", models.PositiveIntegerField(default=0)),
                ("skills_certifications", models.TextField(blank=True)),
                (
                    "preferred_destinations",
                    models.CharField(blank=True, max_length=300),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("screened", "Screened"),
                            ("matched", "Matched to Vacancy"),
                            ("interviewed", "Interviewed"),
                            ("endorsed", "Endorsed"),
                            ("deployed", "Deployed"),
                            ("returned", "Returned"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "occupation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="talent_exchange.occupation",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="talent_exchange.sector",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="deployment",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deployments",
                to="talent_exchange.talentpool",
            ),
        ),
        migrations.CreateModel(
            name="CredentialEndorsement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endorsement_number", models.CharField(max_length=50, unique=True)),
                (
                    "issued_by",
                    models.CharField(
                        default="Abia State Migration Agency", max_length=200
                    ),
                ),
                ("issued_date", models.DateField(auto_now_add=True)),
                ("valid_until", models.DateField()),
                ("destination_country", models.CharField(max_length=100)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("skilled_work", "Skilled Work"),
                            ("domestic_work", "Domestic Work"),
                            ("healthcare", "Healthcare"),
                            ("education", "Education"),
                            ("business", "Business"),
                        ],
                        max_length=100,
                    ),
                ),
                ("verification_hash", models.CharField(blank=True, max_length=64)),
                ("qr_payload", models.CharField(blank=True, max_length=300)),
                ("is_revoked", models.BooleanField(default=False)),
                ("revocation_reason", models.TextField(blank=True)),
                (
                    "deployment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="talent_exchange.deployment",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endorsements",
                        to="talent_exchange.talentpool",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_date"],
            },
        ),
        migrations.CreateModel(
            name="TransparencyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField()),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                        ],
                        default="quarterly",
                        max_length=10,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("quarter", models.PositiveIntegerField(blank=True, null=True)),
                ("workers_deployed_total", models.PositiveIntegerField(default=0)),
                ("workers_by_sector", models.JSONField(default=dict)),
                ("workers_by_destination", models.JSONField(default=dict)),
                ("workers_by_lga", models.JSONField(default=dict)),
                ("avg_salary_by_sector_usd", models.JSONField(default=dict)),
                ("welfare_good_pct", models.PositiveIntegerField(default=0)),
                ("welfare_concern_pct", models.PositiveIntegerField(default=0)),
                ("welfare_critical_pct", models.PositiveIntegerField(default=0)),
                ("employers_verified", models.PositiveIntegerField(default=0)),
                ("employers_blacklisted", models.PositiveIntegerField(default=0)),
                ("endorsements_issued", models.PositiveIntegerField(default=0)),
                ("endorsements_revoked", models.PositiveIntegerField(default=0)),
                ("grievances_open", models.PositiveIntegerField(default=0)),
                ("grievances_resolved", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-snapshot_date"],
                "unique_together": {("year", "quarter", "period_type")},
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vacancy_code", models.CharField(max_length=30, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("positions_available", models.PositiveIntegerField(default=1)),
                ("positions_filled", models.PositiveIntegerField(default=0)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent"),
                            ("contract", "Fixed Contract"),
                            ("seasonal", "Seasonal"),
                            ("domestic", "Domestic Service"),
                        ],
                        max_length=20,
                    ),
                ),
                ("salary_usd", models.DecimalField(decimal_places=2, max_digits=12)),
                ("salary_currency", models.CharField(default="USD", max_length=3)),
                ("accommodation_included", models.BooleanField(default=False)),
                (
                    "accommodation_quality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("good", "Good"),
                            ("adequate", "Adequate"),
                            ("poor", "Poor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location_city", models.CharField(max_length=100)),
                ("location_country", models.CharField(max_length=100)),
                ("requirements", models.TextField(blank=True)),
                ("benefits", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("screening", "Screening"),
                            ("filled", "Filled"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("posted_date", models.DateField(auto_now_add=True)),
                ("closing_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="talent_exchange.foreignemployer",
                    ),
                ),
                (
                    "occupation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="talent_exchange.occupation",
                    ),
                ),
                (
                    "posted_by_mission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="talent_exchange.embassymission",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vacancies",
                "ordering": ["-posted_date"],
            },
        ),
        migrations.AddField(
            model_name="talentpool",
            name="assigned_vacancy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="talent_exchange.vacancy",
            ),
        ),
        migrations.AddField(
            model_name="deployment",
            name="vacancy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deployments",
                to="talent_exchange.vacancy",
            ),
        ),
        migrations.CreateModel(
            name="WelfareCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_date", models.DateField()),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("routine", "Routine 30-day"),
                            ("incident", "Incident-triggered"),
                            ("embassy", "Embassy request"),
                            ("repatriation", "Repatriation assessment"),
                        ],
                        default="routine",
                        max_length=20,
                    ),
                ),
                ("salary_paid_on_time", models.BooleanField(default=True)),
                ("accommodation_acceptable", models.BooleanField(default=True)),
                ("working_hours_compliant", models.BooleanField(default=True)),
                ("medical_access_ok", models.BooleanField(default=True)),
                ("worker_statement", models.TextField(blank=True)),
                ("concerns_raised", models.TextField(blank=True)),
                ("action_taken", models.TextField(blank=True)),
                ("escalated_to_embassy", models.BooleanField(default=False)),
                ("checked_by", models.CharField(blank=True, max_length=200)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welfare_checks",
                        to="talent_exchange.deployment",
                    ),
                ),
            ],
            options={
                "ordering": ["-check_date"],
            },
        ),
    ]
