# Generated by Django 6.0.7 on 2026-08-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talent_exchange", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="embassymission",
            name="blacklist_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="embassymission",
            name="blacklisted_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="embassymission",
            name="is_blacklisted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="foreignemployer",
            name="is_blacklisted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="occupation",
            name="blacklist_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="occupation",
            name="blacklisted_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="occupation",
            name="is_blacklisted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sector",
            name="blacklist_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sector",
            name="blacklisted_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sector",
            name="is_blacklisted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="talentpool",
            name="blacklist_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="talentpool",
            name="blacklisted_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="talentpool",
            name="is_blacklisted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="blacklist_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="blacklisted_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="is_blacklisted",
            field=models.BooleanField(default=False),
        ),
    ]
