# Generated by Django 6.0.7 on 2026-07-18 19:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("migrants", "0004_photouploadqueue_migrantversion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IPFSDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("passport", "Passport"),
                            ("visa", "Visa"),
                            ("id_card", "ID Card"),
                            ("birth_cert", "Birth Certificate"),
                            ("medical", "Medical Record"),
                            ("case_file", "Case File"),
                            ("referral", "Referral Letter"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("cid", models.CharField(blank=True, db_index=True, max_length=128)),
                ("ipfs_gateway_url", models.URLField(blank=True)),
                (
                    "pin_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Upload"),
                            ("pinned", "Pinned on IPFS"),
                            ("failed", "Upload Failed"),
                            ("removed", "Removed from IPFS"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=128)),
                (
                    "local_file",
                    models.FileField(
                        blank=True, null=True, upload_to="ipfs_backups/%Y/%m/"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ipfs_documents",
                        to="cases.case",
                    ),
                ),
                (
                    "migrant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ipfs_documents",
                        to="migrants.migrant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PinQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pin_queue",
                        to="ipfs.ipfsdocument",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
