# Generated by Django 6.0.7 on 2026-07-20 07:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_user_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CBNConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("api_base_url", models.URLField(default="https://api.cbn.gov.ng/v1")),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("client_id", models.CharField(blank=True, max_length=100)),
                ("client_secret", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_sync_enabled", models.BooleanField(default=False)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RemittanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sender_name", models.CharField(max_length=255)),
                (
                    "sender_country",
                    models.CharField(default="United States", max_length=100),
                ),
                ("sender_currency", models.CharField(default="USD", max_length=10)),
                ("amount_sent", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "exchange_rate",
                    models.DecimalField(decimal_places=6, default=0, max_digits=15),
                ),
                (
                    "naira_equivalent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("recipient_name", models.CharField(max_length=255)),
                ("recipient_phone", models.CharField(blank=True, max_length=20)),
                ("recipient_account", models.CharField(blank=True, max_length=50)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("bank", "Bank Transfer"),
                            ("mto", "Money Transfer Operator"),
                            ("crypto", "Cryptocurrency"),
                            ("informal", "Informal / Hawala"),
                            ("mobile", "Mobile Money"),
                        ],
                        default="bank",
                        max_length=20,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                (
                    "transaction_reference",
                    models.CharField(max_length=100, unique=True),
                ),
                ("transaction_date", models.DateTimeField()),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("family_support", "Family Support"),
                            ("business", "Business Investment"),
                            ("education", "Education"),
                            ("healthcare", "Healthcare"),
                            ("real_estate", "Real Estate"),
                            ("other", "Other"),
                        ],
                        default="family_support",
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(default="completed", max_length=20)),
                ("verified_by_cbn", models.BooleanField(default=False)),
                ("cbn_reference", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient_lga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.lga",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date"],
                "indexes": [
                    models.Index(
                        fields=["recipient_lga", "-transaction_date"],
                        name="cbn_remitta_recipie_5a8649_idx",
                    ),
                    models.Index(
                        fields=["channel", "-transaction_date"],
                        name="cbn_remitta_channel_35b5f1_idx",
                    ),
                    models.Index(
                        fields=["status", "-transaction_date"],
                        name="cbn_remitta_status_2aac23_idx",
                    ),
                ],
            },
        ),
    ]
