# Generated by Django 6.0.7 on 2026-08-01 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_collection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="formsubmission",
            index=models.Index(
                fields=["form_type", "created_at"],
                name="data_collec_form_ty_96a08e_idx",
            ),
        ),
    ]
