# Generated by Django 6.0.7 on 2026-07-19 20:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchIndex",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("migrant", "Migrant"),
                            ("case", "Case"),
                            ("referral", "Referral"),
                            ("lga", "LGA"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_id", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
                ("lga_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "title"],
                        name="search_sear_entity__cbf947_idx",
                    ),
                    models.Index(
                        fields=["lga_id"], name="search_sear_lga_id_91b4b5_idx"
                    ),
                    models.Index(
                        fields=["content"], name="search_sear_content_a80c07_idx"
                    ),
                ],
            },
        ),
    ]
