# Generated by Django 6.0.7 on 2026-08-05 03:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CertificateVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate_number", models.CharField(max_length=50, unique=True)),
                ("student_name", models.CharField(max_length=200)),
                ("course_title", models.CharField(max_length=300)),
                ("issue_date", models.DateField()),
                ("accredited_by", models.CharField(blank=True, max_length=200)),
                ("is_valid", models.BooleanField(default=True)),
                ("revocation_reason", models.TextField(blank=True)),
                ("verified_count", models.PositiveIntegerField(default=0)),
                ("last_verified", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Certificate Record",
                "verbose_name_plural": "Certificate Records",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="CourseCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("basic", "Basic / Introductory"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("diploma", "Diploma"),
                            ("professional", "Professional Certification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration_hours", models.PositiveIntegerField()),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[
                            ("in_person", "In-Person"),
                            ("online", "Online"),
                            ("hybrid", "Hybrid"),
                            ("self_paced", "Self-Paced"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("health", "Health"),
                            ("tech", "Technology"),
                            ("trades", "Trades"),
                            ("agriculture", "Agriculture"),
                            ("business", "Business"),
                            ("creative", "Creative Arts"),
                        ],
                        max_length=100,
                    ),
                ),
                ("learning_outcomes", models.TextField(blank=True)),
                ("prerequisites", models.TextField(blank=True)),
                ("is_accredited", models.BooleanField(default=False)),
                ("accreditation_body", models.CharField(blank=True, max_length=200)),
                ("partner_institution", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cohort_number", models.PositiveIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("facilitator", models.CharField(blank=True, max_length=200)),
                ("venue", models.CharField(blank=True, max_length=200)),
                ("max_students", models.PositiveIntegerField(default=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("enrolling", "Open for Enrollment"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                (
                    "japa_program_session",
                    models.CharField(
                        blank=True,
                        help_text="Link to japa_development.ProgramSession ID if cross-referenced",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohorts",
                        to="institute.coursecatalog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cohort",
                "verbose_name_plural": "Cohorts",
                "ordering": ["-start_date"],
                "unique_together": {("course", "cohort_number")},
            },
        ),
        migrations.CreateModel(
            name="ExamSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_title", models.CharField(max_length=200)),
                ("exam_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=120)),
                ("venue", models.CharField(blank=True, max_length=200)),
                ("max_score", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="institute.cohort",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Schedule",
                "verbose_name_plural": "Exam Schedules",
                "ordering": ["-exam_date"],
            },
        ),
        migrations.CreateModel(
            name="PartnerInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("polytechnic", "Polytechnic"),
                            ("university", "University"),
                            ("vocational", "Vocational Center"),
                            ("ngo", "NGO / CSO"),
                            ("private", "Private Sector"),
                            ("government", "Government Agency"),
                            ("international", "International Organization"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("mou_signed", models.BooleanField(default=False)),
                ("mou_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "courses_offered",
                    models.ManyToManyField(
                        blank=True,
                        related_name="partner_institutions",
                        to="institute.coursecatalog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner Institution",
                "verbose_name_plural": "Partner Institutions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("lga", models.CharField(blank=True, max_length=100)),
                (
                    "japa_beneficiary_id",
                    models.CharField(
                        blank=True,
                        help_text="Link to japa_development.Beneficiary",
                        max_length=50,
                    ),
                ),
                ("enrollment_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("dropped", "Dropped"),
                            ("suspended", "Suspended"),
                        ],
                        default="enrolled",
                        max_length=20,
                    ),
                ),
                (
                    "final_score",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("certificate_issued", models.BooleanField(default=False)),
                (
                    "certificate_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("certificate_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="institute.cohort",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Enrollment",
                "verbose_name_plural": "Student Enrollments",
                "ordering": ["-enrollment_date"],
                "unique_together": {("cohort", "full_name", "phone")},
            },
        ),
    ]
