# Generated by Django 6.0.7 on 2026-07-20 07:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WBConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "api_base_url",
                    models.URLField(default="https://api.worldbank.org/v2"),
                ),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_sync_enabled", models.BooleanField(default=False)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="WBIndicator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("indicator_code", models.CharField(max_length=50, unique=True)),
                ("indicator_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(default="general", max_length=50)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("source_note", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["indicator_code"],
            },
        ),
        migrations.CreateModel(
            name="WBDataPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("country_code", models.CharField(max_length=10)),
                ("country_name", models.CharField(max_length=100)),
                ("year", models.PositiveIntegerField()),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=20, null=True
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_points",
                        to="worldbank.wbindicator",
                    ),
                ),
            ],
            options={
                "ordering": ["-year"],
                "indexes": [
                    models.Index(
                        fields=["indicator", "country_code", "-year"],
                        name="worldbank_w_indicat_240c81_idx",
                    )
                ],
                "unique_together": {("indicator", "country_code", "year")},
            },
        ),
    ]
