# Generated by Django 6.0.7 on 2026-07-20 07:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ECOWASConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("api_base_url", models.URLField(default="https://ecowas.int/api/v1")),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_sync_enabled", models.BooleanField(default=False)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ECOWASMigrantFlow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("country_of_origin", models.CharField(max_length=100)),
                ("country_of_destination", models.CharField(max_length=100)),
                (
                    "migration_type",
                    models.CharField(
                        choices=[
                            ("labour", "Labour Migration"),
                            ("forced", "Forced Migration"),
                            ("irregular", "Irregular Migration"),
                            ("student", "Student Migration"),
                            ("trade", "Trade-Related Movement"),
                        ],
                        default="labour",
                        max_length=20,
                    ),
                ),
                ("sector", models.CharField(blank=True, max_length=100)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("age_group", models.CharField(blank=True, max_length=20)),
                ("estimated_count", models.PositiveIntegerField(default=0)),
                ("year", models.PositiveIntegerField()),
                (
                    "protocol_article",
                    models.CharField(
                        blank=True,
                        help_text="ECOWAS Free Movement Protocol article",
                        max_length=50,
                    ),
                ),
                (
                    "data_source",
                    models.CharField(default="ECOWAS Commission", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-year", "-estimated_count"],
                "indexes": [
                    models.Index(
                        fields=["country_of_origin", "-year"],
                        name="ecowas_ecow_country_8cd499_idx",
                    ),
                    models.Index(
                        fields=["migration_type", "-year"],
                        name="ecowas_ecow_migrati_68d88e_idx",
                    ),
                    models.Index(
                        fields=["sector", "-year"], name="ecowas_ecow_sector_22ed7a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ECOWASTradeFlow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reporter_country", models.CharField(max_length=100)),
                ("partner_country", models.CharField(max_length=100)),
                ("product_category", models.CharField(max_length=100)),
                (
                    "export_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "import_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "data_source",
                    models.CharField(default="ECOWAS Trade Observatory", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-year"],
                "indexes": [
                    models.Index(
                        fields=["reporter_country", "partner_country", "-year"],
                        name="ecowas_ecow_reporte_26f801_idx",
                    )
                ],
            },
        ),
    ]
