# Generated by Django 5.2.16 on 2026-07-13 21:24

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicFieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("migrant", "Migrant"),
                            ("case", "Case"),
                            ("referral", "Referral"),
                            ("trader", "Trader"),
                            ("shipment", "Shipment"),
                            ("customs_procedure", "Customs Procedure"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("field_name", models.SlugField(max_length=100)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("datetime", "DateTime"),
                            ("choice", "Single Choice"),
                            ("multi_choice", "Multiple Choice"),
                            ("email", "Email"),
                            ("phone", "Phone Number"),
                            ("url", "URL"),
                            ("json", "JSON"),
                            ("geojson", "GeoJSON (Point/Polygon)"),
                            ("file", "File Upload"),
                            ("image", "Image Upload"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("choices", models.JSONField(blank=True, null=True)),
                ("default_value", models.JSONField(blank=True, null=True)),
                ("is_required", models.BooleanField(default=False)),
                ("is_sensitive", models.BooleanField(default=False)),
                ("is_searchable", models.BooleanField(default=True)),
                (
                    "partner_org",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("validation_regex", models.CharField(blank=True, max_length=500)),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                ("max_length", models.PositiveIntegerField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_dynamic_fields",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dynamic Field Definition",
                "verbose_name_plural": "Dynamic Field Definitions",
                "ordering": ["entity_type", "order", "field_name"],
            },
        ),
        migrations.CreateModel(
            name="DynamicFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(db_index=True, max_length=50)),
                ("entity_id", models.PositiveIntegerField(db_index=True)),
                ("value", models.JSONField(blank=True, null=True)),
                ("encrypted_value", models.BinaryField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_dynamic_values",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="dynamic_fields.dynamicfielddefinition",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_dynamic_values",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dynamic Field Value",
                "verbose_name_plural": "Dynamic Field Values",
            },
        ),
        migrations.CreateModel(
            name="EntityDynamicData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(db_index=True, max_length=50)),
                ("entity_id", models.PositiveIntegerField(db_index=True)),
                ("data", models.JSONField(default=dict)),
                ("search_vector", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Entity Dynamic Data",
                "verbose_name_plural": "Entity Dynamic Data",
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="dynamic_fie_entity__69df30_idx",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["data"],
                        name="idx_entity_data_gin",
                        opclasses=["jsonb_path_ops"],
                    ),
                ],
                "unique_together": {("entity_type", "entity_id")},
            },
        ),
        migrations.AddIndex(
            model_name="dynamicfielddefinition",
            index=models.Index(
                fields=["entity_type", "is_active"],
                name="dynamic_fie_entity__fc3941_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dynamicfielddefinition",
            index=models.Index(
                fields=["partner_org", "category"],
                name="dynamic_fie_partner_862bad_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dynamicfielddefinition",
            unique_together={("entity_type", "field_name")},
        ),
        migrations.AddIndex(
            model_name="dynamicfieldvalue",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="dynamic_fie_entity__8a5903_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dynamicfieldvalue",
            index=models.Index(
                fields=["entity_type", "entity_id", "definition"],
                name="idx_dynamic_lookup",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dynamicfieldvalue",
            unique_together={("definition", "entity_type", "entity_id")},
        ),
    ]
