# Generated by Django 6.0.7 on 2026-08-05 03:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiasporaPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("association_name", models.CharField(max_length=300)),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("contact_person", models.CharField(max_length=200)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("letter_of_cooperation_signed", models.BooleanField(default=False)),
                ("signed_date", models.DateField(blank=True, null=True)),
                ("nominated_volunteers_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Diaspora Partner",
                "verbose_name_plural": "Diaspora Partners",
                "ordering": ["association_name"],
            },
        ),
        migrations.CreateModel(
            name="TrainingModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_number", models.PositiveIntegerField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("pass_mark", models.PositiveIntegerField(default=80)),
                (
                    "institute_course_code",
                    models.CharField(
                        blank=True,
                        help_text="Link to Institute CourseCatalog code",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Training Module",
                "verbose_name_plural": "Training Modules",
                "ordering": ["module_number"],
            },
        ),
        migrations.CreateModel(
            name="CertifiedVolunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("other_names", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "photograph",
                    models.ImageField(blank=True, upload_to="corps/photos/"),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                ("lga", models.CharField(max_length=100)),
                ("town_union", models.CharField(max_length=200)),
                (
                    "proof_document",
                    models.FileField(blank=True, upload_to="corps/proofs/"),
                ),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applicant", "Applicant"),
                            ("in_training", "In Training"),
                            ("certified", "Certified"),
                            ("suspended", "Suspended"),
                            ("decertified", "Decertified"),
                        ],
                        default="applicant",
                        max_length=20,
                    ),
                ),
                (
                    "certification_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("authority_letter_issued", models.BooleanField(default=False)),
                (
                    "authority_letter_valid_until",
                    models.DateField(blank=True, null=True),
                ),
                ("qr_code_verification", models.CharField(blank=True, max_length=200)),
                ("deployment_country", models.CharField(blank=True, max_length=100)),
                ("deployment_city", models.CharField(blank=True, max_length=100)),
                ("hours_served_monthly", models.PositiveIntegerField(default=0)),
                ("hours_served_total", models.PositiveIntegerField(default=0)),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                (
                    "institute_student_id",
                    models.CharField(
                        blank=True,
                        help_text="Link to Institute StudentEnrollment",
                        max_length=50,
                    ),
                ),
                (
                    "referee_diaspora_assoc",
                    models.CharField(blank=True, max_length=200),
                ),
                ("referee_town_union", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_slo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slo_volunteers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Certified Volunteer",
                "verbose_name_plural": "Certified Volunteers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CorpsLeadership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("president", "President"),
                            ("vp_europe_americas", "VP — Europe & Americas"),
                            ("vp_africa_middle_east", "VP — Africa & Middle East"),
                            ("vp_asia_oceania", "VP — Asia & Oceania"),
                            ("secretary_general", "Secretary-General"),
                            ("treasurer", "Treasurer"),
                            ("ethics_chair", "Chair — Ethics & Disciplinary"),
                        ],
                        max_length=30,
                    ),
                ),
                ("term_start", models.DateField()),
                ("term_end", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leadership_roles",
                        to="migration_corps.certifiedvolunteer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leadership Position",
                "verbose_name_plural": "Leadership Positions",
                "ordering": ["role"],
            },
        ),
        migrations.CreateModel(
            name="EthicsComplaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complainant_name", models.CharField(max_length=200)),
                ("complainant_contact", models.CharField(blank=True, max_length=200)),
                (
                    "complaint_type",
                    models.CharField(
                        choices=[
                            ("confidentiality_breach", "Breach of Confidentiality"),
                            ("exploitation", "Exploitation or Harm"),
                            ("impersonation", "Impersonation or False Representation"),
                            ("political_partisan", "Political Partisan Activity"),
                            ("fraud", "Fraud or Embezzlement"),
                            ("misconduct", "General Misconduct"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("evidence", models.FileField(blank=True, upload_to="corps/ethics/")),
                ("committee_findings", models.TextField(blank=True)),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("warning", "Written Warning"),
                            ("suspension", "Suspension"),
                            ("decertification", "Decertification"),
                            ("law_enforcement", "Referral to Law Enforcement"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_investigation", "Under Investigation"),
                            ("resolved", "Resolved"),
                            ("appealed", "Appealed to IMGP"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("appeal_to_imgp", models.BooleanField(default=False)),
                ("imgp_decision", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateField(blank=True, null=True)),
                (
                    "respondent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ethics_complaints",
                        to="migration_corps.certifiedvolunteer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ethics Complaint",
                "verbose_name_plural": "Ethics Complaints",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WelfareContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("migrant_name", models.CharField(blank=True, max_length=200)),
                ("migrant_phone", models.CharField(blank=True, max_length=20)),
                ("migrant_email", models.EmailField(blank=True, max_length=254)),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("welcome_orientation", "Welcome & Orientation"),
                            ("welfare_check", "Welfare Monitoring"),
                            ("info_guidance", "Information & Guidance"),
                            ("referral", "Referral Service"),
                            ("crisis_response", "Crisis Response"),
                            ("community_building", "Community Building"),
                            ("circular_migration", "Circular Migration Promotion"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("referral_made", models.BooleanField(default=False)),
                ("referral_to", models.CharField(blank=True, max_length=200)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("contact_date", models.DateField()),
                ("anonymised_data_submitted", models.BooleanField(default=False)),
                (
                    "observatory_person_id",
                    models.CharField(
                        blank=True,
                        help_text="Link to Observatory Migrant",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welfare_contacts",
                        to="migration_corps.certifiedvolunteer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Welfare Contact",
                "verbose_name_plural": "Welfare Contacts",
                "ordering": ["-contact_date"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("hours_served", models.PositiveIntegerField(default=0)),
                ("migrants_contacted_count", models.PositiveIntegerField(default=0)),
                ("welfare_checks_count", models.PositiveIntegerField(default=0)),
                ("referrals_made_count", models.PositiveIntegerField(default=0)),
                ("community_events_count", models.PositiveIntegerField(default=0)),
                ("report_submitted_at", models.DateTimeField(auto_now_add=True)),
                ("slo_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("slo_feedback", models.TextField(blank=True)),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="migration_corps.certifiedvolunteer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly Activity Log",
                "verbose_name_plural": "Monthly Activity Logs",
                "ordering": ["-year", "-month"],
                "unique_together": {("volunteer", "month", "year")},
            },
        ),
        migrations.CreateModel(
            name="CountryCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("europe_americas", "Europe & the Americas"),
                            ("africa_middle_east", "Africa & the Middle East"),
                            ("asia_oceania", "Asia & Oceania"),
                        ],
                        max_length=20,
                    ),
                ),
                ("active_status", models.BooleanField(default=True)),
                ("monthly_report_due", models.PositiveIntegerField(default=1)),
                (
                    "coordinator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clusters_coordinated",
                        to="migration_corps.certifiedvolunteer",
                    ),
                ),
                (
                    "volunteers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="clusters",
                        to="migration_corps.certifiedvolunteer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country Cluster",
                "verbose_name_plural": "Country Clusters",
                "ordering": ["country", "city"],
                "unique_together": {("country", "city")},
            },
        ),
        migrations.CreateModel(
            name="VolunteerTrainingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "score",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("passed", models.BooleanField(default=False)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="migration_corps.trainingmodule",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_progress",
                        to="migration_corps.certifiedvolunteer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Progress",
                "verbose_name_plural": "Training Progress Records",
                "unique_together": {("volunteer", "module")},
            },
        ),
    ]
