# Generated by Django 6.0.7 on 2026-08-05 01:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("other_names", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not", "Prefer not to say"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "lga",
                    models.CharField(max_length=100, verbose_name="LGA (Abia State)"),
                ),
                ("ward", models.CharField(blank=True, max_length=100)),
                ("community", models.CharField(blank=True, max_length=200)),
                ("education_level", models.CharField(blank=True, max_length=50)),
                (
                    "baseline_status",
                    models.CharField(
                        choices=[
                            ("unemployed", "Unemployed"),
                            ("student", "Student"),
                            ("employed", "Employed"),
                            ("self_employed", "Self-employed"),
                            ("migrant_abroad", "Migrant Abroad"),
                            ("returnee", "Returnee"),
                            ("aspiring_migrant", "Aspiring Migrant"),
                        ],
                        default="aspiring_migrant",
                        max_length=20,
                    ),
                ),
                ("primary_skill", models.CharField(blank=True, max_length=200)),
                ("secondary_skill", models.CharField(blank=True, max_length=200)),
                (
                    "skill_sector",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("health", "Health"),
                            ("tech", "Technology & Digital"),
                            ("trades", "Trades & Manufacturing"),
                            ("agriculture", "Agriculture"),
                            ("education", "Education"),
                            ("business", "Business & Entrepreneurship"),
                            ("creative", "Creative Arts"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                ("enrolled_date", models.DateField(auto_now_add=True)),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("active", "Active in Program"),
                            ("completed_training", "Completed Training"),
                            ("migrated_regular", "Migrated — Regular Pathway"),
                            ("migrated_irregular", "Migrated — Irregular Pathway"),
                            ("employed_local", "Employed Locally"),
                            ("self_employed_local", "Self-employed Locally"),
                            ("returned", "Returned"),
                            ("reintegrated", "Reintegrated"),
                            ("dropped_out", "Dropped Out"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("status_changed_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "current_location_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("abia", "Abia State"),
                            ("se_other", "Other South East"),
                            ("other_ng", "Other Nigeria"),
                            ("abroad", "Abroad"),
                        ],
                        max_length=20,
                    ),
                ),
                ("current_country", models.CharField(blank=True, max_length=100)),
                ("current_state", models.CharField(blank=True, max_length=100)),
                ("current_city", models.CharField(blank=True, max_length=100)),
                (
                    "monthly_remittance_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "remittance_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annually", "Annually"),
                            ("irregular", "Irregular"),
                        ],
                        max_length=20,
                    ),
                ),
                ("willing_to_invest", models.BooleanField(default=False)),
                ("willing_to_mentor", models.BooleanField(default=False)),
                ("willing_to_return", models.BooleanField(default=False)),
                ("willing_to_volunteer", models.BooleanField(default=False)),
                (
                    "observatory_person_id",
                    models.CharField(
                        blank=True,
                        help_text="ID in abia.migrants if cross-referenced",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Beneficiary",
                "verbose_name_plural": "Beneficiaries",
                "ordering": ["-enrolled_date"],
            },
        ),
        migrations.CreateModel(
            name="PolicyEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "pillar_focus",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("p1", "Pillar 1"),
                            ("p2", "Pillar 2"),
                            ("p3", "Pillar 3"),
                            ("p4", "Pillar 4"),
                            ("all", "All Pillars"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "data_sources",
                    models.TextField(
                        help_text="Which tracker queries or reports generated this evidence"
                    ),
                ),
                ("key_findings", models.TextField(blank=True)),
                ("policy_brief_url", models.URLField(blank=True)),
                (
                    "policy_brief_file",
                    models.FileField(blank=True, upload_to="policy_briefs/"),
                ),
                ("submitted_to", models.CharField(blank=True, max_length=300)),
                ("submission_date", models.DateField(blank=True, null=True)),
                ("decision_outcome", models.TextField(blank=True)),
                ("outcome_date", models.DateField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Policy Evidence",
                "verbose_name_plural": "Policy Evidence",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StakeholderEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "partner",
                    models.CharField(
                        choices=[
                            ("iom", "International Organization for Migration (IOM)"),
                            (
                                "ncfrmi",
                                "National Commission for Refugees, Migrants and IDPs (NCFRMI)",
                            ),
                            ("csonetmade", "CSOnetMADE"),
                            ("ama", "Abia Migration Agency (AMA)"),
                            ("polytechnic", "Ogbonnaya Onu Polytechnic"),
                            ("state_govt", "Abia State Government"),
                            ("federal_govt", "Federal Government Agency"),
                            ("diaspora_assoc", "Diaspora Association"),
                            ("private_sector", "Private Sector Partner"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("partner_other", models.CharField(blank=True, max_length=200)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("training", "Training Delivery"),
                            ("counseling", "Counseling Support"),
                            ("funding", "Funding / Grant"),
                            ("technical", "Technical Assistance"),
                            ("policy", "Policy Dialogue"),
                            ("monitoring", "Monitoring Visit"),
                            ("research", "Joint Research"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "pillar",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("p1", "Pillar 1 — Migration Governance & Information"),
                            ("p2", "Pillar 2 — Language & Cultural Competency"),
                            ("p3", "Pillar 3 — Skills Development & Certification"),
                            ("p4", "Pillar 4 — Return & Reintegration Support"),
                        ],
                        max_length=2,
                    ),
                ),
                ("beneficiaries_reached", models.PositiveIntegerField(default=0)),
                (
                    "value_ngn",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("engagement_date", models.DateField()),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Stakeholder Engagement",
                "verbose_name_plural": "Stakeholder Engagements",
                "ordering": ["-engagement_date"],
            },
        ),
        migrations.CreateModel(
            name="ProgramOutcomeSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField()),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                        ],
                        default="quarterly",
                        max_length=10,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "quarter",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "month",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ("p1_counseled_total", models.PositiveIntegerField(default=0)),
                ("p1_counseled_target", models.PositiveIntegerField(default=0)),
                ("p1_regular_pathway_uptake", models.PositiveIntegerField(default=0)),
                ("p1_irregular_pathway_uptake", models.PositiveIntegerField(default=0)),
                ("p1_trafficking_referrals", models.PositiveIntegerField(default=0)),
                ("p1_info_sessions_held", models.PositiveIntegerField(default=0)),
                ("p1_materials_distributed", models.PositiveIntegerField(default=0)),
                ("p2_language_enrolled_total", models.PositiveIntegerField(default=0)),
                (
                    "p2_cultural_orientation_completed",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "p2_avg_integration_readiness",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("p3_trained_total", models.PositiveIntegerField(default=0)),
                ("p3_trained_target", models.PositiveIntegerField(default=0)),
                ("p3_certifications_issued", models.PositiveIntegerField(default=0)),
                ("p3_placed_employed", models.PositiveIntegerField(default=0)),
                ("p3_placed_self_employed", models.PositiveIntegerField(default=0)),
                ("p3_placed_abroad", models.PositiveIntegerField(default=0)),
                ("p3_unemployed", models.PositiveIntegerField(default=0)),
                ("p4_returnees_supported", models.PositiveIntegerField(default=0)),
                ("p4_returnees_target", models.PositiveIntegerField(default=0)),
                ("p4_reintegration_packages", models.PositiveIntegerField(default=0)),
                ("p4_micro_enterprises", models.PositiveIntegerField(default=0)),
                ("p4_micro_enterprises_target", models.PositiveIntegerField(default=0)),
                ("p4_businesses_surviving_6mo", models.PositiveIntegerField(default=0)),
                (
                    "p4_businesses_surviving_12mo",
                    models.PositiveIntegerField(default=0),
                ),
                ("p4_alumni_active", models.PositiveIntegerField(default=0)),
                (
                    "total_budget_period",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_spent_period",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "p1_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "p2_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "p3_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "p4_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("count_abia", models.PositiveIntegerField(default=0)),
                ("count_se_other", models.PositiveIntegerField(default=0)),
                ("count_other_ng", models.PositiveIntegerField(default=0)),
                ("count_abroad", models.PositiveIntegerField(default=0)),
                ("count_male", models.PositiveIntegerField(default=0)),
                ("count_female", models.PositiveIntegerField(default=0)),
                ("count_other_gender", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("generated_by", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Program Outcome Snapshot",
                "verbose_name_plural": "Program Outcome Snapshots",
                "ordering": ["-snapshot_date"],
                "unique_together": {("year", "quarter", "month", "period_type")},
            },
        ),
        migrations.CreateModel(
            name="PillarParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pillar",
                    models.CharField(
                        choices=[
                            ("p1", "Pillar 1 — Migration Governance & Information"),
                            ("p2", "Pillar 2 — Language & Cultural Competency"),
                            ("p3", "Pillar 3 — Skills Development & Certification"),
                            ("p4", "Pillar 4 — Return & Reintegration Support"),
                        ],
                        max_length=2,
                    ),
                ),
                ("enrolled_date", models.DateField()),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("dropped_out", models.BooleanField(default=False)),
                ("dropout_reason", models.TextField(blank=True)),
                (
                    "counseling_sessions_attended",
                    models.PositiveIntegerField(default=0),
                ),
                ("total_counseling_sessions", models.PositiveIntegerField(default=0)),
                (
                    "migration_pathway",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("student_visa", "Student Visa"),
                            ("skilled_worker", "Skilled Worker Visa"),
                            ("family_reunion", "Family Reunion"),
                            ("business_visa", "Business Visa"),
                            ("tourist_visa", "Tourist Visa"),
                            ("irregular", "Irregular Route"),
                            ("undecided", "Undecided"),
                        ],
                        max_length=50,
                    ),
                ),
                ("destination_country", models.CharField(blank=True, max_length=100)),
                (
                    "trafficking_vulnerability_baseline",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "trafficking_vulnerability_exit",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("protection_referral_made", models.BooleanField(default=False)),
                ("protection_referral_date", models.DateField(blank=True, null=True)),
                (
                    "language_course",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("german", "German"),
                            ("french", "French"),
                            ("arabic", "Arabic"),
                            ("italian", "Italian"),
                            ("spanish", "Spanish"),
                            ("portuguese", "Portuguese"),
                            ("chinese", "Chinese"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "language_proficiency_baseline",
                    models.CharField(blank=True, max_length=10),
                ),
                (
                    "language_proficiency_exit",
                    models.CharField(blank=True, max_length=10),
                ),
                (
                    "cultural_orientation_modules",
                    models.PositiveIntegerField(default=0),
                ),
                ("cultural_orientation_completed", models.BooleanField(default=False)),
                (
                    "integration_readiness_score",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("training_sector", models.CharField(blank=True, max_length=100)),
                ("training_hours_completed", models.PositiveIntegerField(default=0)),
                ("training_hours_total", models.PositiveIntegerField(default=0)),
                ("certification_issued", models.BooleanField(default=False)),
                (
                    "certification_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("national", "National Certificate"),
                            ("international", "International Certificate"),
                            ("industry", "Industry-Recognized"),
                            ("vocational", "Vocational Diploma"),
                        ],
                        max_length=100,
                    ),
                ),
                ("certification_body", models.CharField(blank=True, max_length=200)),
                ("certification_date", models.DateField(blank=True, null=True)),
                (
                    "skills_market_alignment_score",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "placement_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("employed_domestic", "Employed — Domestic"),
                            ("employed_abroad", "Employed — Abroad"),
                            ("self_employed", "Self-employed"),
                            ("unemployed", "Unemployed"),
                            ("further_study", "Further Study"),
                        ],
                        max_length=30,
                    ),
                ),
                ("placement_employer", models.CharField(blank=True, max_length=200)),
                ("placement_date", models.DateField(blank=True, null=True)),
                (
                    "placement_salary_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("returnee_needs_assessment", models.TextField(blank=True)),
                (
                    "reintegration_package_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash_grant", "Cash Grant"),
                            ("equipment", "Equipment / Tools"),
                            ("training", "Skills Training"),
                            ("psychosocial", "Psychosocial Support"),
                            ("housing", "Housing Support"),
                            ("combined", "Combined Package"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "reintegration_package_value_ngn",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("reintegration_package_delivered", models.BooleanField(default=False)),
                ("reintegration_package_date", models.DateField(blank=True, null=True)),
                ("business_incubation_enrolled", models.BooleanField(default=False)),
                ("mentor_assigned", models.CharField(blank=True, max_length=200)),
                ("micro_enterprise_registered", models.BooleanField(default=False)),
                ("business_cac_number", models.CharField(blank=True, max_length=20)),
                ("business_sector", models.CharField(blank=True, max_length=100)),
                ("business_employees", models.PositiveIntegerField(default=0)),
                ("alumni_network_member", models.BooleanField(default=False)),
                ("alumni_engagement_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pillar_participations",
                        to="japa_development.beneficiary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pillar Participation",
                "verbose_name_plural": "Pillar Participations",
                "ordering": ["-enrolled_date"],
                "unique_together": {("beneficiary", "pillar")},
            },
        ),
    ]
