# Generated by Django 6.0.7 on 2026-08-05 01:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("japa_development", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facilitator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "facilitator_type",
                    models.CharField(
                        choices=[
                            ("internal", "Internal Staff"),
                            ("external", "External Consultant"),
                            ("volunteer", "Volunteer"),
                            ("diaspora", "Diaspora Mentor"),
                        ],
                        default="external",
                        max_length=20,
                    ),
                ),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("expertise_sectors", models.CharField(blank=True, max_length=300)),
                ("bio", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Facilitator",
                "verbose_name_plural": "Facilitators",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="TrainingInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ict", "ICT Equipment"),
                            ("tool", "Hand Tools / Machinery"),
                            ("material", "Raw Material"),
                            ("stationery", "Stationery"),
                            ("ppe", "PPE / Safety Gear"),
                            ("furniture", "Furniture"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("quantity_on_hand", models.PositiveIntegerField(default=0)),
                ("quantity_issued", models.PositiveIntegerField(default=0)),
                (
                    "unit_cost_ngn",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("supplier", models.CharField(blank=True, max_length=200)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Storage location / warehouse",
                        max_length=200,
                    ),
                ),
                ("reorder_level", models.PositiveIntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Training Inventory Item",
                "verbose_name_plural": "Training Inventory Items",
                "ordering": ["category", "item_name"],
            },
        ),
        migrations.CreateModel(
            name="ProgramSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("session_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("venue", models.CharField(blank=True, max_length=200)),
                ("facilitator", models.CharField(blank=True, max_length=200)),
                ("max_participants", models.PositiveIntegerField(default=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("postponed", "Postponed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "materials_used",
                    models.TextField(
                        blank=True, help_text="List of training materials consumed"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pillar_participation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="japa_development.pillarparticipation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Session",
                "verbose_name_plural": "Program Sessions",
                "ordering": ["-session_date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("excused", "Excused"),
                            ("late", "Late"),
                        ],
                        default="present",
                        max_length=10,
                    ),
                ),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "participation_score",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="japa_development.beneficiary",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="japa_development.programsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "unique_together": {("session", "beneficiary")},
            },
        ),
    ]
