# Generated by Django 6.0.7 on 2026-07-19 00:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                            ("ad_hoc", "Ad-hoc"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "data",
                    models.JSONField(default=dict, help_text="Generated report data"),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("view", "View"),
                            ("export", "Export"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("failed_login", "Failed Login"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Model name e.g. migrants.Migrant", max_length=50
                    ),
                ),
                ("entity_id", models.CharField(blank=True, max_length=100)),
                (
                    "entity_repr",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable identifier",
                        max_length=255,
                    ),
                ),
                ("old_values", models.JSONField(blank=True, default=dict)),
                ("new_values", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Reason for the change"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="audit_audit_user_id_429f6b_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_audit_entity__9535bf_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="audit_audit_action_0c6a84_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-created_at"],
                        name="audit_audit_ip_addr_ff6f1d_idx",
                    ),
                ],
            },
        ),
    ]
