# Generated by Django 6.0.7 on 2026-07-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="entity_repr",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="entity_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="compliancereport",
            name="data",
            field=models.JSONField(default=dict),
        ),
    ]
