# Generated by Django 6.0.7 on 2026-07-20 07:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WTOConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "api_base_url",
                    models.URLField(default="https://api.wto.org/timeseries/v1"),
                ),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_sync_enabled", models.BooleanField(default=False)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TradeRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "flow_type",
                    models.CharField(
                        choices=[
                            ("export", "Export"),
                            ("import", "Import"),
                            ("re_export", "Re-Export"),
                        ],
                        max_length=20,
                    ),
                ),
                ("product_category", models.CharField(max_length=100)),
                ("hs_code", models.CharField(blank=True, max_length=20)),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("agriculture", "Agriculture"),
                            ("manufacturing", "Manufacturing"),
                            ("mining", "Mining"),
                            ("services", "Services"),
                            ("textiles", "Textiles"),
                            ("technology", "Technology"),
                        ],
                        default="manufacturing",
                        max_length=20,
                    ),
                ),
                ("value_usd", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("quantity_unit", models.CharField(blank=True, max_length=20)),
                ("trade_partner", models.CharField(max_length=100)),
                ("partner_country_code", models.CharField(max_length=10)),
                (
                    "reporter_country",
                    models.CharField(default="Nigeria", max_length=100),
                ),
                ("year", models.PositiveIntegerField()),
                ("quarter", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "labour_intensity_score",
                    models.PositiveIntegerField(
                        default=0, help_text="0-100 estimate of labour intensity"
                    ),
                ),
                ("data_source", models.CharField(default="WTO", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-year", "-value_usd"],
                "indexes": [
                    models.Index(
                        fields=["sector", "-year"], name="wto_tradere_sector_3f3562_idx"
                    ),
                    models.Index(
                        fields=["flow_type", "-year"],
                        name="wto_tradere_flow_ty_5b66df_idx",
                    ),
                    models.Index(
                        fields=["trade_partner", "-year"],
                        name="wto_tradere_trade_p_dd210e_idx",
                    ),
                ],
            },
        ),
    ]
