# Generated by Django 6.0.7 on 2026-07-20 07:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SportsConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "data_source_name",
                    models.CharField(default="Transfermarkt API", max_length=100),
                ),
                (
                    "api_base_url",
                    models.URLField(default="https://api.transfermarkt.com/v1"),
                ),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_sync_enabled", models.BooleanField(default=False)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AthleteProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nationality", models.CharField(default="Nigeria", max_length=100)),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("football", "Football"),
                            ("basketball", "Basketball"),
                            ("athletics", "Athletics"),
                            ("boxing", "Boxing"),
                            ("tennis", "Tennis"),
                            ("cricket", "Cricket"),
                            ("rugby", "Rugby"),
                            ("other", "Other"),
                        ],
                        default="football",
                        max_length=20,
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=50)),
                ("current_club", models.CharField(blank=True, max_length=255)),
                ("current_country", models.CharField(blank=True, max_length=100)),
                (
                    "market_value_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "origin_lga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.lga",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="AthleteTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_club", models.CharField(max_length=255)),
                ("from_country", models.CharField(max_length=100)),
                ("to_club", models.CharField(max_length=255)),
                ("to_country", models.CharField(max_length=100)),
                (
                    "transfer_fee_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent Transfer"),
                            ("loan", "Loan"),
                            ("free_transfer", "Free Transfer"),
                            ("youth_promotion", "Youth Promotion"),
                            ("return", "Return from Abroad"),
                        ],
                        default="permanent",
                        max_length=20,
                    ),
                ),
                ("transfer_date", models.DateField()),
                ("contract_end_date", models.DateField(blank=True, null=True)),
                ("agent_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rumoured", "Rumoured"),
                            ("negotiating", "Negotiating"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "is_international",
                    models.BooleanField(
                        default=False, help_text="Cross-border transfer"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="sports.athleteprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-transfer_date"],
            },
        ),
        migrations.AddIndex(
            model_name="athleteprofile",
            index=models.Index(
                fields=["sport", "origin_lga"], name="sports_athl_sport_d04ea4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="athleteprofile",
            index=models.Index(
                fields=["nationality", "is_active"],
                name="sports_athl_nationa_f69e06_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="athletetransfer",
            index=models.Index(
                fields=["athlete", "-transfer_date"],
                name="sports_athl_athlete_f10e10_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="athletetransfer",
            index=models.Index(
                fields=["to_country", "-transfer_date"],
                name="sports_athl_to_coun_fd0901_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="athletetransfer",
            index=models.Index(
                fields=["is_international", "-transfer_date"],
                name="sports_athl_is_inte_7fc9e4_idx",
            ),
        ),
    ]
